version: "3.9"
services:
  tarkov-net:
    container_name: tarkov-net
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://YOUR_UNRAID_IP:3000
      NEXTAUTH_SECRET: change-me
      DATABASE_URL: file:/app/data/games.db?connection_limit=1
      WORKER_LOG_LEVEL: info
      STARTUP_LOG_LEVEL: info
      PUBG_CRAWLER_LOG_LEVEL: info
      MANUAL_PUBG_LOG_LEVEL: info
      CLEAN_NEXT_LOG_LEVEL: info
      ENABLE_PUBG_CRAWLER: "1"
      TWITCH_CLIENT_ID: change-me
      TWITCH_CLIENT_SECRET: change-me
      TWITCH_EVENTSUB_SECRET: change-me
      TWITCH_EVENTSUB_CALLBACK_URL: https://YOUR_DOMAIN/api/twitch/eventsub/stream-online
      AUTO_EVENTSUB_SYNC: "1"
      EVENTSUB_SYNC_INTERVAL_MS: "1800000"
      EVENTSUB_SYNC_LIMIT: "400"
      EVENTSUB_CREATE_LIMIT_PER_SYNC: "80"
      PUBG_TWITCH_GAME_IDS: "493057,27971"
    volumes:
      - ./data:/app/data
